name: portwhine
description: "Portwhine is a customizable software for monitoring and automated checking of IT assets."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^11.1.0
  bloc: ^9.1.0
  chopper: ^8.3.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  fluttertoast: ^9.0.0
  google_fonts: ^6.3.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  chopper_generator: ^8.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/